version: "3.9"

services:
  app:
    build: .
    container_name: referral-app
    environment:
      DATABASE_URL: postgres://anmol:anmol@db:5432/referral_db
      JWT_SECRET: your_secret_key
      FRONTEND_URL: http://localhost:4000
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: referral-db
    environment:
      POSTGRES_DB: referral_db
      POSTGRES_USER: anmol
      POSTGRES_PASSWORD: anmol
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: referral-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
